// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/auth/auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type CheckRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e5b8102c891c02, []int{0}
}

func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (m *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(m, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

func (m *CheckRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type CheckResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e5b8102c891c02, []int{1}
}

func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (m *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(m, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

func (m *CheckResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckRequest)(nil), "CheckRequest")
	proto.RegisterType((*CheckResponse)(nil), "CheckResponse")
}

func init() { proto.RegisterFile("protos/auth/auth.proto", fileDescriptor_b6e5b8102c891c02) }

var fileDescriptor_b6e5b8102c891c02 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x86, 0x2d, 0x54, 0xc5, 0xc3, 0x3a, 0x64, 0x90, 0xe2, 0x24, 0x99, 0xea, 0x92, 0x94, 0xfa,
	0x04, 0xea, 0x1b, 0x74, 0x74, 0xbb, 0xd4, 0xd0, 0x14, 0x9b, 0xa6, 0x36, 0x97, 0xf7, 0x17, 0x82,
	0x85, 0xba, 0x1c, 0xf7, 0x1f, 0xdf, 0x7d, 0xfc, 0x70, 0x1c, 0x27, 0x47, 0xce, 0x4b, 0x0c, 0x64,
	0xe2, 0x10, 0xf1, 0xc0, 0x39, 0xec, 0x1f, 0x46, 0x37, 0xef, 0x5a, 0x7f, 0x82, 0xf6, 0xc4, 0x18,
	0xa4, 0x03, 0x5a, 0x9d, 0x27, 0xe7, 0xa4, 0xd8, 0xd5, 0x71, 0xe7, 0x17, 0xc8, 0x7e, 0x8c, 0x1f,
	0xdd, 0xe0, 0x35, 0xcb, 0x61, 0x6b, 0xb5, 0xf7, 0xd8, 0xce, 0xdc, 0x1c, 0xab, 0x12, 0xd2, 0x5b,
	0x20, 0xc3, 0x0a, 0x58, 0xc7, 0x17, 0x96, 0x89, 0xa5, 0xfe, 0x74, 0x10, 0x7f, 0x26, 0xbe, 0xba,
	0x57, 0xcf, 0xb2, 0xed, 0xc8, 0x04, 0x25, 0x1a, 0x67, 0x25, 0xaa, 0x57, 0xe8, 0x27, 0x34, 0x16,
	0x07, 0xec, 0x1d, 0x61, 0xa7, 0x3a, 0x69, 0xb1, 0x99, 0x9c, 0x5c, 0xf4, 0x57, 0x9b, 0x18, 0xae,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0x67, 0x73, 0x49, 0xd5, 0x00, 0x00, 0x00,
}
